server {
    listen 80;
    server_name ${PORTAINER_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name ${EXPRESS_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name ${CPO_SERVER_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name ${CPO_DASHBOARD_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name ${CPO_ODATA_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name ${CPO_OCPI_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name ${CPO_OCPP_JSON_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name ${CPO_OCPP_SOAP_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name ${CPO_DASHBOARD_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}

server {
    listen 80;
    server_name ${CPO_ADMIN_SUB_DOMAIN};
    location / {
        root /var/www/certbot;
    }
}
